project:
  type: book
  output-dir: docs
  
book:
  title: "Hands-On Programming with R"
  author: "Garrett Grolemund"
  cover-image: images/cover.png
  site-url: https://cynkra.github.io/hopr/
  repo-url: https://github.com/cynkra/hopr/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - preface.qmd
    - part: dice.qmd
      chapters: 
        - basics.qmd
        - packages.qmd
    - part: cards.qmd
      chapters:
        - objects.qmd
        - notation.qmd
        - modifying.qmd
        - environments.qmd
    - part: slots.qmd
      chapters:
        - programs.qmd
        - s3.qmd
        - loops.qmd
        - speed.qmd
  appendices:
    - a1-starting.qmd
    - a2-packages.qmd
    - a3-updating.qmd
    - a4-data.qmd
    - a5-debug.qmd 

format:
  html: 
    theme: cosmo
    cover-image: cover.png
    code-link: true


